version: '3.8'

services:
  backend:
    image: seifeddine77/souqtech-backend:latest
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    networks:
      - souqtech-net

  frontend:
    image: seifeddine77/souqtech-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - souqtech-net

networks:
  souqtech-net:
    driver: bridge
