apiVersion: v1
kind: Service
metadata:
  name: souqtech-backend-service
  namespace: souqtech
spec:
  selector:
    app: souqtech-backend
  ports:
    - name: http
      port: 80
      targetPort: 8081
      nodePort: 30080
    - name: metrics
      port: 8081
      targetPort: 8081
  type: NodePort
