apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: souqtech
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==       # root
  MYSQL_USER: c291cXRlY2g=            # souqtech (base64)
  MYSQL_PASSWORD: c291cXRlY2g=        # souqtech (base64)
