apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: souqtech
type: Opaque
stringData:
  # ⚠️ IMPORTANT: Changez ces valeurs avant le déploiement en production !
  # Pour générer: openssl rand -base64 32
  MYSQL_ROOT_PASSWORD: "MyS3cur3R00tP@ssw0rd!2026"
  MYSQL_USER: "souqtech"
  MYSQL_PASSWORD: "S0uqT3ch$3cur3P@ss2026!"
